# Generated by Django 3.0.3 on 2020-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
